routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/
Auth::routes();

Route::view('/', 'start');

Route::get('/search', 'CatalogController@search');

Route::get('/tree', 'CatalogController@getTreeView');

Route::resource('/list','CatalogController');

app/Catalog.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    protected $fillable = ['name', 'position', 'employment', 'salary', 'chief_id'];


    //  One-to-Many Relationships with DB
    public function childs()
    {
        return $this->hasMany(Catalog::class, 'chief_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Catalog;
use Illuminate\Http\Request;

class CatalogController extends Controller
{
    public function search(Request $request)
    {
        $query = $request->input('query');
        $employee = Catalog::where('name', 'LIKE', '%'.$query.'%')
                ->orWhere('position', 'LIKE', '%'.$query.'%')
                ->orWhere('employment', 'LIKE', '%'.$query.'%')
                ->orWhere('salary', 'LIKE', '%'.$query.'%')
                ->paginate(11);
        return view('catalogs.search')->withDetails($employee)->withQuery($query);
    }


    public function getTreeView()
    {
        $catalogs = Catalog::where('chief_id', '=', 0)->with('childs')->get();
        return view ('catalogs.treeview', compact('catalogs'));
    }


    //  Display all information from the database as a list with pagination and sorting
    public function index(Request $request)
    {
        $sort = $request->get('sort', null);

        $employees = Catalog::when(request('sort'), function ($query) use ($sort) {
            $query->orderBy($sort, 'desc');
        })->paginate(11);

        return view ('catalogs.listview', compact('employees'));
    }


    public function create()
    {
        return view('employees.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3',
            'position' => 'required',
            'employment' => 'required|max:10',
            'salary' => 'required|max:4',
            'chief_id' => 'required',
        ]);

        Catalog::create($request->all());
        return redirect()->route('list.index')->with('status','Employee created successfully');
    }


    public function show($id)
    {
        $employee = Catalog::find($id);
        return view('employees.show',compact('employee'));
    }


    public function edit($id)
    {
        $employee = Catalog::find($id);
        return view('employees.edit',compact('employee'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|min:3',
            'position' => 'required',
            'employment' => 'required|max:10',
            'salary' => 'required|max:4',
            'chief_id' => 'required',
        ]);

        Catalog::find($id)->update($request->all());
        return redirect()->route('list.index')->with('status','Employee updated successfully');
    }


    public function destroy($id)
    {
        Catalog::find($id)->delete();
        return redirect()->route('list.index')->with('status','Employee deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/catalogs/listview.blade.php
@extends ('layouts.app', ['title' => 'Employees List'])

@section ('content')
<div class="container">
    <h3 class="text-center">Employees List</h3>
    <div class="panel panel-default table-responsive">

        {{--Flash a success message--}}
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <table class="table table-bordered table-hover">
            @include('layouts.tables.header')

            @foreach($employees as $employee)
                @include('layouts.tables.data')
            @endforeach
        </table>

    </div>
</div>

    {{-- Add Pagination To View  --}}
<div class="container">
    <nav aria-label="Page navigation" class="text-center">

        {{ $employees->appends(request()->all())->links() }}

    </nav>
</div>

@endsection

resources/views/catalogs/manageChild.blade.php
<ul>
@foreach($childs as $child)
    <li>
        {{ $child->name }}
        {{ $child->position }}
        @if(count($child->childs)>0)
            @include('catalogs.manageChild', ['childs' => $child->childs])
         @endif
    </li>
@endforeach
</ul>

resources/views/catalogs/search.blade.php
@extends ('layouts.app', ['title' => 'Serch Result'])

@section ('content')
<div class="container">
    <h3 class="text-center">Serch Result for {{ $query }}</h3>
    <div class="panel panel-default">

        <table class="table table-bordered table-hover tablesorter">
            @include('layouts.tables.header')

            @if(isset($details))
                @foreach($details as $employee)
                    @include('layouts.tables.data')
                @endforeach
            @endif
        </table>

    </div>
</div>

    {{-- Add Pagination To View  --}}
<div class="container">
    <nav aria-label="Page navigation" class="text-center">
        {{ $details->appends(Request::only('query'))->render() }}
    </nav>
</div>

@endsection

resources/views/catalogs/treeview.blade.php
@extends ('layouts.app', ['title' => 'Employees Tree'])

@section ('content')
<div class="container">
    <h3>Employees Tree</h3>
    <div class="panel panel-default">
        <ul id="tree1">

            @foreach($catalogs as $catalog)
                <li>
                    {{ $catalog->name }}
                    {{ $catalog->position }}

                    @if(count($catalog->childs)>0)
                        @include('catalogs.manageChild',['childs' => $catalog->childs])
                    @endif
                </li>
            @endforeach

        </ul>
    </div>
</div>

@endsection

@section ('script')
<script src="{{asset('js/treeview.js')}}"></script>
@endsection

resources/views/employees/create.blade.php
@extends ('layouts.app', ['title' => 'Create Employees'])

@section ('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create Employees</div>

                {{-- Check on errors --}}
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif



                {{-- Form connection --}}
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="/list">
                        {{ csrf_field() }}
                        @include('layouts.form')
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/employees/edit.blade.php
@extends ('layouts.app', ['title' => 'Edit Employee'])

@section ('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Employee</div>

                {{-- Check on errors --}}
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                {{-- Form connection --}}
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ url('list', [$employee->id]) }}">
                        <input type="hidden" name="_method" value="PUT">
                        {{ csrf_field() }}
                        @include('layouts.form')
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/employees/show.blade.php
@extends ('layouts.app', ['title' => 'Prewiew Employee'])

@section ('content')
<div class="container">
    <h3 class="text-center">Employee {{ $employee->name }} Info</h3>
    <div class="panel panel-default">
        <table class="table table-bordered table-hover tablesorter">

            @include('layouts.tables.header')
            @include('layouts.tables.data')

        </table>
    </div>
</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title ?? '' }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/treeview.css" rel="stylesheet">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                        <li><a href="/tree">Employees Tree</a></li>
                        <!-- When authorizing, display additional links -->
                        @if (Auth::check())
                        <li><a href="{{ route('list.index') }}">Employees List</a></li>
                        <li><a href="{{ route('list.create') }}">Add New Employee</a></li>
                        @endif
                    </ul>


                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>

                    @if (Auth::check())
                    <form class="navbar-form navbar-right" method="GET" action="/search">
                        <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search" name="query">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    @endif

                </div>
            </div>
        </nav>
    </div>

    @yield('content')

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('script')

</body>
</html>

resources/views/layouts/form.blade.php
<div class="form-group">
    <label for="name" class="col-md-4 control-label">Name</label>
    <div class="col-md-6">
        <input id="name" type="text" class="form-control" name="name" placeholder="Full Name"
        value="{{ old('name',$employee->name ?? '') }}">
    </div>
</div>

<div class="form-group">
    <label for="position" class="col-md-4 control-label">Position</label>
    <div class="col-md-6">
        <select class="form-control" name="position">
            <option>{{ old('position',$employee->position ?? 'Position') }}</option>
            <option value="ceo">CEO</option>
            <option value="execute_chief">Execute Chief</option>
            <option value="producer">Producer</option>
            <option value="manager">Manager</option>
            <option value="seller">Seller</option>
        </select>

    </div>
</div>

<div class="form-group">
    <label for="employment" class="col-md-4 control-label" >Employment</label>
    <div class="col-md-6">
        <input id="employment" type="text" class="form-control" name="employment" placeholder="Employment"
                value="{{ old('employment',$employee->employment ?? '') }}">
    </div>
</div>

<div class="form-group">
    <label for="salary" class="col-md-4 control-label">Salary</label>
    <div class="col-md-6">
        <input id="salary" type="text" class="form-control" name="salary" placeholder="Salary"
                value="{{ old('salary',$employee->salary ?? '') }}">
    </div>
</div>

<div class="form-group">
    <label for="chief_id" class="col-md-4 control-label">Chief ID</label>
    <div class="col-md-6">
        <input id="chief_id" type="text" class="form-control" name="chief_id" placeholder="Find ID in List :)"
                value="{{ old('chief_id',$employee->chief_id ?? '') }}">
        <!-- <select class="form-control" >
            <option>Choose chief</option>
            <option>CEO</option>
            <option>Execute Chief</option>
            <option>Producer</option>
            <option>Manager</option>
            <option>Seller</option>
        </select> -->
    </div>
</div>

<div class="form-group">
    <div class="col-md-6 col-md-offset-4">
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
        <a class="btn btn-link" href="{{ url('list') }}">
            Back
        </a>
    </div>
</div>

resources/views/layouts/tables/data.blade.php
<tr>
    <td>{{ $employee->id }}</td>
    <td><a href="/list/{{$employee->id}}">{{ $employee->name }}</a></td>
    <td>{{ $employee->position }}</td>
    <td>{{ $employee->employment }}</td>
    <td>{{ $employee->salary }}</td>
    <td><a class="btn btn-info btn-sm" href="{{ url('list/' . $employee->id . '/edit') }}">Edit</a>
        <form action="{{url('list', [$employee->id])}}" method="POST" style="display:inline">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <input type="submit" class="btn btn-danger btn-sm" value="Delete"/>
        </form>
    </td>
</tr>

resources/views/layouts/tables/header.blade.php
<tr>
    <th width="80px">
        <a href="{{ route('list.index', ['sort' => 'id']) }}">id</a></th>
    <th width="240px">
        <a href="{{ route('list.index', ['sort' => 'name']) }}">Name</a></th>
    <th width="160px">
        <a href="{{ route('list.index', ['sort' => 'position']) }}">Position</a></th>
    <th width="160">
        <a href="{{ route('list.index', ['sort' => 'employment']) }}">Employment</a></th>
    <th width="80px">
        <a href="{{ route('list.index', ['sort' => 'salary']) }}">Salary</a></th>
    <th width="160px">Action</th>
</tr>

resources/views/start.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>ABZ Category Catalog</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
                <div class="title m-b-md">
                    ABZ Category Catalog
                </div>

                <div class="links">
                    <a href="{{ url('tree') }}">Employees Tree</a>

                    @if (Route::has('login'))
                    @auth
                        <a href="{{ url('list') }}">Employees List</a>
                        <a href="{{ url('list/create') }}">Add New Employee</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>
                        <a href="{{ route('register') }}">Register</a>
                    @endauth
                    @endif
                </div>

            </div>
        </div>
    </body>
</html>